name: 'close stale issues'
on:
  workflow_dispatch:
  schedule:
    - cron: '00 10 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v8
        with:
          stale-issue-message: 'This issue is stale'
          days-before-stale: 7
          days-before-close: 0
          days-before-pr-stale: -1
          days-before-pr-close: -1
          operations-per-run: 1000
